### ISSUE TITLE
Path not used when finding Dockerfile

### ISSUE THREAD

**Issue by foucdeg** [CircleCI-Public/azure-acr-orb#4]
### Orb version

0.1.1

### What happened

The documentation of the "path" parameter of the job states "Path to the directory containing your Dockerfile and build context. Defaults to . (working directory)."
I would therefore expect that this parameter be used to find the Dockerfile.

### Expected behavior

The build_image job looks for the dockerfile at `{{ path }}/Dockerfile` (unless the `dockerfile` parameter is specified)

### Actual behavior

The build_image job looks for the dockerfile at ./Dockerfile, ignoring the path. The build fails because the Dockerfile is not found.

Example build: https://circleci.com/gh/safecube/iot-container-tracker/26
In the failing step, I expected the Dockerfile to be looked for under `$HOME/project/server` (the value of the path parameter).

### My analysis

The issue seems to be at this line:  https://github.com/CircleCI-Public/azure-acr-orb/blob/master/src/commands/build-image.yml#L44

The parameter `<<parameters.path>>` should be used before `<<parameters.dockerfile>>`.
Either that or the documentation for the parameter path, which is currently misleading, should specify that `path` is not used to look for the Dockerfile.

**Comment by iynere** [comment]
thank you @foucdeg 

we already have a docker orb with a perfectly good `build` command, actually, which already addresses this issue, so i think to fix this issue here, we'll just drop in the docker orb's build command, rather than having this orb re-code it from scratch

**Comment by iynere** [comment]
should be patched in `circleci/azure-acr@0.1.2` @foucdeg
