### ISSUE TITLE
Support for building/pushing images with multiple tags

### ISSUE THREAD

**Issue by jonadaly** [CircleCI-Public/azure-acr-orb#9]
### Orb version
0.1.3

### What happened
The orb commands don't support multiple tags. For example, to use the `azure-acr/build-and-push-image` command to create an image with 3 tags, you need to use three different steps.

### Expected behaviour
It should be possible to build and push an image with multiple tags with one command.

The docker orb used by this ACR orb has since been updated to support multiple tags (see https://github.com/CircleCI-Public/docker-orb/issues/36), so this should be a case of simply bumping the version of the docker orb.

I've raised a PR to do this: https://github.com/CircleCI-Public/azure-acr-orb/pull/8

**Comment by lokst** [comment]
@jonadaly Closing this issue as you have since resolved it with https://github.com/CircleCI-Public/azure-acr-orb/pull/8 🙏
